<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.7 PH Acerca de Contrastes para el vector de medias Poblacional \(\underline{\boldsymbol{\mu}}\), de una \(N_p(\underline{\boldsymbol{\mu}} \ , \ \mathbf{\Sigma} )\) | Chapter 4</title>
  <meta name="description" content="Este libro contine ……" />
  <meta name="generator" content="bookdown 0.30 and GitBook 2.6.7" />

  <meta property="og:title" content="4.7 PH Acerca de Contrastes para el vector de medias Poblacional \(\underline{\boldsymbol{\mu}}\), de una \(N_p(\underline{\boldsymbol{\mu}} \ , \ \mathbf{\Sigma} )\) | Chapter 4" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/imagenes/imagen1.png" />
  <meta property="og:description" content="Este libro contine ……" />
  <meta name="github-repo" content="raperezaga/iam" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.7 PH Acerca de Contrastes para el vector de medias Poblacional \(\underline{\boldsymbol{\mu}}\), de una \(N_p(\underline{\boldsymbol{\mu}} \ , \ \mathbf{\Sigma} )\) | Chapter 4" />
  
  <meta name="twitter:description" content="Este libro contine ……" />
  <meta name="twitter:image" content="/imagenes/imagen1.png" />




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-observaciones-pareadas.html"/>
<link rel="next" href="inferencia-para-la-matriz-de-covarianza.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preámbulo</a>
<ul>
<li class="chapter" data-level="" data-path="dedicación.html"><a href="dedicación.html"><i class="fa fa-check"></i>Dedicación</a></li>
<li class="chapter" data-level="" data-path="agradecimientos.html"><a href="agradecimientos.html"><i class="fa fa-check"></i>Agradecimientos</a></li>
<li class="chapter" data-level="" data-path="paquetes-usados-en-el-libro.html"><a href="paquetes-usados-en-el-libro.html"><i class="fa fa-check"></i>Paquetes usados en el libro</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="rep_al.html"><a href="rep_al.html"><i class="fa fa-check"></i><b>1</b> Repaso de álgebra lineal</a>
<ul>
<li class="chapter" data-level="1.1" data-path="acb_al.html"><a href="acb_al.html"><i class="fa fa-check"></i><b>1.1</b> Algunos conceptos básicos</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="acb_al.html"><a href="acb_al.html#matrices"><i class="fa fa-check"></i><b>1.1.1</b> Matrices</a></li>
<li class="chapter" data-level="1.1.2" data-path="acb_al.html"><a href="acb_al.html#vectores"><i class="fa fa-check"></i><b>1.1.2</b> Vectores</a></li>
<li class="chapter" data-level="1.1.3" data-path="acb_al.html"><a href="acb_al.html#operaciones-matrices"><i class="fa fa-check"></i><b>1.1.3</b> Operaciones Matriciales</a></li>
<li class="chapter" data-level="1.1.4" data-path="acb_al.html"><a href="acb_al.html#matrices-especiales"><i class="fa fa-check"></i><b>1.1.4</b> Matrices Especiales</a></li>
<li class="chapter" data-level="1.1.5" data-path="acb_al.html"><a href="acb_al.html#descomp-espectral"><i class="fa fa-check"></i><b>1.1.5</b> Descomposición Espectral de una Matriz (eigen-descomposición)</a></li>
<li class="chapter" data-level="1.1.6" data-path="acb_al.html"><a href="acb_al.html#eigen-descom-msdp"><i class="fa fa-check"></i><b>1.1.6</b> Descomposición Espectral de Matrices Simétricas Definidas (o Semidefinidas) Positivas</a></li>
<li class="chapter" data-level="1.1.7" data-path="acb_al.html"><a href="acb_al.html#traza-determinante-y-rango-de-una-matriz"><i class="fa fa-check"></i><b>1.1.7</b> Traza, Determinante y Rango de una Matriz</a></li>
<li class="chapter" data-level="1.1.8" data-path="acb_al.html"><a href="acb_al.html#formas-cuadraticas"><i class="fa fa-check"></i><b>1.1.8</b> Formas Cuadráticas</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="algunas-propiedades-estadísticas-de-la-eigen-descomposición-de-una-matriz.html"><a href="algunas-propiedades-estadísticas-de-la-eigen-descomposición-de-una-matriz.html"><i class="fa fa-check"></i><b>1.2</b> Algunas Propiedades Estadísticas de la Eigen-Descomposición de una Matriz</a></li>
<li class="chapter" data-level="1.3" data-path="diferenc_vectores.html"><a href="diferenc_vectores.html"><i class="fa fa-check"></i><b>1.3</b> Diferenciación con Vectores y Matrices</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="diferenc_vectores.html"><a href="diferenc_vectores.html#vector-gradiente-para-diferentes-definiciones-de-funderlinex"><i class="fa fa-check"></i><b>1.3.1</b> Vector-Gradiente para diferentes definiciones de <span class="math inline">\(f(\underline{x})\)</span>:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="org_pres_dat.html"><a href="org_pres_dat.html"><i class="fa fa-check"></i><b>2</b> Organización y Presentación de Datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="resumenes-descriptivos.html"><a href="resumenes-descriptivos.html"><i class="fa fa-check"></i><b>2.1</b> Resumenes Descriptivos</a></li>
<li class="chapter" data-level="2.2" data-path="representación-gráfica-de-observaciones-multivariadas.html"><a href="representación-gráfica-de-observaciones-multivariadas.html"><i class="fa fa-check"></i><b>2.2</b> Representación Gráfica de Observaciones multivariadas</a></li>
<li class="chapter" data-level="2.3" data-path="vectores-y-matrices-aleatorias.html"><a href="vectores-y-matrices-aleatorias.html"><i class="fa fa-check"></i><b>2.3</b> Vectores y Matrices Aleatorias</a></li>
<li class="chapter" data-level="2.4" data-path="vectores-y-matrices-poblacionales-particionados.html"><a href="vectores-y-matrices-poblacionales-particionados.html"><i class="fa fa-check"></i><b>2.4</b> Vectores y Matrices Poblacionales Particionados</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="vectores-y-matrices-poblacionales-particionados.html"><a href="vectores-y-matrices-poblacionales-particionados.html#particionamiento-del-vector-de-medias-poblacionales"><i class="fa fa-check"></i><b>2.4.1</b> Particionamiento del Vector de Medias-Poblacionales</a></li>
<li class="chapter" data-level="2.4.2" data-path="vectores-y-matrices-poblacionales-particionados.html"><a href="vectores-y-matrices-poblacionales-particionados.html#particionamiento-de-la-matriz-de-var-cov-poblacional-mathbfsigma"><i class="fa fa-check"></i><b>2.4.2</b> Particionamiento de la Matriz de Var-Cov Poblacional <span class="math inline">\(\mathbf{\Sigma}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="propiedades-sobre-la-media-y-varianza-de-combinaciones-lineales.html"><a href="propiedades-sobre-la-media-y-varianza-de-combinaciones-lineales.html"><i class="fa fa-check"></i><b>2.5</b> Propiedades Sobre la Media y Varianza de Combinaciones Lineales</a></li>
<li class="chapter" data-level="2.6" data-path="vectores-y-matrices-muestrales-particionadas.html"><a href="vectores-y-matrices-muestrales-particionadas.html"><i class="fa fa-check"></i><b>2.6</b> Vectores y Matrices Muestrales Particionadas</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="vectores-y-matrices-muestrales-particionadas.html"><a href="vectores-y-matrices-muestrales-particionadas.html#particionamiento-del-vector-de-medias-muestrales"><i class="fa fa-check"></i><b>2.6.1</b> Particionamiento del Vector de Medias Muestrales</a></li>
<li class="chapter" data-level="2.6.2" data-path="vectores-y-matrices-muestrales-particionadas.html"><a href="vectores-y-matrices-muestrales-particionadas.html#particionamiento-de-la-matriz-de-var-cov-muestrales"><i class="fa fa-check"></i><b>2.6.2</b> Particionamiento de la Matriz de Var-Cov Muestrales</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="algunas-formas-matriciales-eficientes.html"><a href="algunas-formas-matriciales-eficientes.html"><i class="fa fa-check"></i><b>2.7</b> Algunas formas matriciales Eficientes</a></li>
<li class="chapter" data-level="2.8" data-path="propiedades-sobre-la-media-y-varianza-muestral-de-combinaciones-lineales.html"><a href="propiedades-sobre-la-media-y-varianza-muestral-de-combinaciones-lineales.html"><i class="fa fa-check"></i><b>2.8</b> Propiedades Sobre la Media y Varianza Muestral de Combinaciones Lineales</a></li>
<li class="chapter" data-level="2.9" data-path="varianza-generalizada-muestral-y-su-interpretación-geométrica.html"><a href="varianza-generalizada-muestral-y-su-interpretación-geométrica.html"><i class="fa fa-check"></i><b>2.9</b> Varianza Generalizada Muestral y su Interpretación Geométrica</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="varianza-generalizada-muestral-y-su-interpretación-geométrica.html"><a href="varianza-generalizada-muestral-y-su-interpretación-geométrica.html#interpretación-geométrica-1-de-la-varianza-generalizada"><i class="fa fa-check"></i><b>2.9.1</b> Interpretación Geométrica-1 de la Varianza Generalizada</a></li>
<li class="chapter" data-level="2.9.2" data-path="varianza-generalizada-muestral-y-su-interpretación-geométrica.html"><a href="varianza-generalizada-muestral-y-su-interpretación-geométrica.html#interpretación-geométrica-2-de-la-varianza-generalizada"><i class="fa fa-check"></i><b>2.9.2</b> Interpretación Geométrica-2 de la Varianza Generalizada</a></li>
<li class="chapter" data-level="2.9.3" data-path="varianza-generalizada-muestral-y-su-interpretación-geométrica.html"><a href="varianza-generalizada-muestral-y-su-interpretación-geométrica.html#varianza-generalizada-determinada-por-la-matriz-de-correlación-muestral-mathbfr"><i class="fa fa-check"></i><b>2.9.3</b> Varianza Generalizada Determinada por la Matriz de Correlación Muestral <span class="math inline">\(\mathbf{R}\)</span></a></li>
<li class="chapter" data-level="2.9.4" data-path="varianza-generalizada-muestral-y-su-interpretación-geométrica.html"><a href="varianza-generalizada-muestral-y-su-interpretación-geométrica.html#relación-entre-mathbfs-y-mathbfr"><i class="fa fa-check"></i><b>2.9.4</b> Relación entre <span class="math inline">\(|\mathbf{S}|\)</span> y <span class="math inline">\(|\mathbf{R}|\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="varianza-total-muestral.html"><a href="varianza-total-muestral.html"><i class="fa fa-check"></i><b>2.10</b> Varianza Total Muestral</a></li>
<li class="chapter" data-level="2.11" data-path="muestra-aleatoria-de-distribuciones-p-variadas.html"><a href="muestra-aleatoria-de-distribuciones-p-variadas.html"><i class="fa fa-check"></i><b>2.11</b> Muestra Aleatoria de Distribuciones <span class="math inline">\(p\)</span>-Variadas</a></li>
<li class="chapter" data-level="2.12" data-path="distancias.html"><a href="distancias.html"><i class="fa fa-check"></i><b>2.12</b> Distancias</a>
<ul>
<li class="chapter" data-level="2.12.1" data-path="distancias.html"><a href="distancias.html#definición-de-algunas-distancias"><i class="fa fa-check"></i><b>2.12.1</b> Definición de Algunas Distancias</a></li>
<li class="chapter" data-level="2.12.2" data-path="distancias.html"><a href="distancias.html#relación-de-la-distancia-de-mahalanobis-con-la-distribución-chi-cuadrado"><i class="fa fa-check"></i><b>2.12.2</b> Relación de la Distancia de Mahalanobis con la Distribución chi-Cuadrado</a></li>
<li class="chapter" data-level="2.12.3" data-path="distancias.html"><a href="distancias.html#ejemplo"><i class="fa fa-check"></i><b>2.12.3</b> Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Normal-Multiv.html"><a href="Normal-Multiv.html"><i class="fa fa-check"></i><b>3</b> Distribución Normal Multivariada</a>
<ul>
<li class="chapter" data-level="3.1" data-path="geometria-NM.html"><a href="geometria-NM.html"><i class="fa fa-check"></i><b>3.1</b> Geometría y propiedades de la NM</a></li>
<li class="chapter" data-level="3.2" data-path="normal-univariada.html"><a href="normal-univariada.html"><i class="fa fa-check"></i><b>3.2</b> Normal Univariada</a></li>
<li class="chapter" data-level="3.3" data-path="normal-multivariada.html"><a href="normal-multivariada.html"><i class="fa fa-check"></i><b>3.3</b> Normal Multivariada</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="normal-multivariada.html"><a href="normal-multivariada.html#algunos-aspectos-geométricos-de-la-nm"><i class="fa fa-check"></i><b>3.3.1</b> Algunos Aspectos Geométricos de la NM</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="prop-nm.html"><a href="prop-nm.html"><i class="fa fa-check"></i><b>3.4</b> Propiedades de la distribución Normal Multivariada</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="prop-nm.html"><a href="prop-nm.html#prop1"><i class="fa fa-check"></i><b>3.4.1</b> <strong>Propiedad-1:</strong></a></li>
<li class="chapter" data-level="3.4.2" data-path="prop-nm.html"><a href="prop-nm.html#prop2"><i class="fa fa-check"></i><b>3.4.2</b> <strong>Propiedad-2:</strong></a></li>
<li class="chapter" data-level="3.4.3" data-path="prop-nm.html"><a href="prop-nm.html#prop3"><i class="fa fa-check"></i><b>3.4.3</b> <strong>Propiedad-3:</strong></a></li>
<li class="chapter" data-level="3.4.4" data-path="prop-nm.html"><a href="prop-nm.html#prop4"><i class="fa fa-check"></i><b>3.4.4</b> <strong>Propiedad-4:</strong></a></li>
<li class="chapter" data-level="3.4.5" data-path="prop-nm.html"><a href="prop-nm.html#prop5"><i class="fa fa-check"></i><b>3.4.5</b> <strong>Propiedad-5:</strong></a></li>
<li class="chapter" data-level="3.4.6" data-path="prop-nm.html"><a href="prop-nm.html#prop6"><i class="fa fa-check"></i><b>3.4.6</b> <strong>Propiedad-6:</strong></a></li>
<li class="chapter" data-level="3.4.7" data-path="prop-nm.html"><a href="prop-nm.html#prop7"><i class="fa fa-check"></i><b>3.4.7</b> <strong>Propiedad-7:</strong></a></li>
<li class="chapter" data-level="3.4.8" data-path="prop-nm.html"><a href="prop-nm.html#prop8"><i class="fa fa-check"></i><b>3.4.8</b> <strong>Propiedad-8:</strong></a></li>
<li class="chapter" data-level="3.4.9" data-path="prop-nm.html"><a href="prop-nm.html#prop9"><i class="fa fa-check"></i><b>3.4.9</b> <strong>Propiedad-9:</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="evaluación-del-supuesto-de-normalidad-multivariada.html"><a href="evaluación-del-supuesto-de-normalidad-multivariada.html"><i class="fa fa-check"></i><b>3.5</b> Evaluación del Supuesto de Normalidad Multivariada</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="evaluación-del-supuesto-de-normalidad-multivariada.html"><a href="evaluación-del-supuesto-de-normalidad-multivariada.html#evaluación-a-nivel-marginal-ie.-normalidad-univariada"><i class="fa fa-check"></i><b>3.5.1</b> Evaluación a nivel marginal (ie. Normalidad Univariada)</a></li>
<li class="chapter" data-level="3.5.2" data-path="evaluación-del-supuesto-de-normalidad-multivariada.html"><a href="evaluación-del-supuesto-de-normalidad-multivariada.html#evaluación-de-la-normalidad-bi-variada"><i class="fa fa-check"></i><b>3.5.2</b> Evaluación de la Normalidad Bi-variada</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="detección-de-observaciones-atípicas.html"><a href="detección-de-observaciones-atípicas.html"><i class="fa fa-check"></i><b>3.6</b> Detección de Observaciones Atípicas</a></li>
<li class="chapter" data-level="3.7" data-path="transformaciones-para-acercar-a-la-normalidad-multivariada.html"><a href="transformaciones-para-acercar-a-la-normalidad-multivariada.html"><i class="fa fa-check"></i><b>3.7</b> Transformaciones para Acercar a la Normalidad Multivariada</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="transformaciones-para-acercar-a-la-normalidad-multivariada.html"><a href="transformaciones-para-acercar-a-la-normalidad-multivariada.html#familia-de-transformaciones-de-potencia-de-box-y-cox-1964"><i class="fa fa-check"></i><b>3.7.1</b> Familia de Transformaciones de Potencia de Box y Cox (1964)</a></li>
<li class="chapter" data-level="3.7.2" data-path="transformaciones-para-acercar-a-la-normalidad-multivariada.html"><a href="transformaciones-para-acercar-a-la-normalidad-multivariada.html#transformaciones-para-el-caso-multivariado"><i class="fa fa-check"></i><b>3.7.2</b> Transformaciones para el Caso Multivariado:</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="muestra-aleatoria-normal-p-variada.html"><a href="muestra-aleatoria-normal-p-variada.html"><i class="fa fa-check"></i><b>3.8</b> Muestra Aleatoria Normal <span class="math inline">\(p\)</span>-Variada</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="muestra-aleatoria-normal-p-variada.html"><a href="muestra-aleatoria-normal-p-variada.html#estimadores-de-máx-ver-de-una-normal-multivariada"><i class="fa fa-check"></i><b>3.8.1</b> Estimadores de Máx-Ver de una Normal-Multivariada</a></li>
<li class="chapter" data-level="3.8.2" data-path="muestra-aleatoria-normal-p-variada.html"><a href="muestra-aleatoria-normal-p-variada.html#distribución-muestral-de-overlineunderlinemathbfx-y-mathbfs_n"><i class="fa fa-check"></i><b>3.8.2</b> Distribución Muestral de <span class="math inline">\(\overline{\underline{\mathbf{x}}}\)</span> y <span class="math inline">\(\mathbf{S}_n\)</span></a></li>
<li class="chapter" data-level="3.8.3" data-path="muestra-aleatoria-normal-p-variada.html"><a href="muestra-aleatoria-normal-p-variada.html#comportamiento-de-underlineoverlinemathbfx_p-y-mathbfs-para-tamaños-muestrales-grandes"><i class="fa fa-check"></i><b>3.8.3</b> Comportamiento de <span class="math inline">\(\underline{\overline{\mathbf{x}}}_p\)</span> y <span class="math inline">\(\mathbf{S}\)</span> para Tamaños Muestrales Grandes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="inferen-estad.html"><a href="inferen-estad.html"><i class="fa fa-check"></i><b>4</b> Inferencia Estadística</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>4.1</b> Introducción</a></li>
<li class="chapter" data-level="4.2" data-path="inferencia-estadística-para-la-media-mu-caso-univariado.html"><a href="inferencia-estadística-para-la-media-mu-caso-univariado.html"><i class="fa fa-check"></i><b>4.2</b> Inferencia Estadística para la Media (<span class="math inline">\(\mu\)</span>)-caso univariado</a></li>
<li class="chapter" data-level="4.3" data-path="pruebas-de-hipótesis-para-underlineboldsymbolmu.html"><a href="pruebas-de-hipótesis-para-underlineboldsymbolmu.html"><i class="fa fa-check"></i><b>4.3</b> Pruebas de Hipótesis para <span class="math inline">\(\underline{\boldsymbol{\mu}}\)</span></a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="pruebas-de-hipótesis-para-underlineboldsymbolmu.html"><a href="pruebas-de-hipótesis-para-underlineboldsymbolmu.html#pruebas-de-hipótesis-para-underlineboldsymbolmu-cuando-mathbfsigma-es-desconocida-normal"><i class="fa fa-check"></i><b>4.3.1</b> Pruebas de Hipótesis para <span class="math inline">\(\underline{\boldsymbol{\mu}}\)</span> cuando <span class="math inline">\(\mathbf{\Sigma}\)</span> es Desconocida (Normal)</a></li>
<li class="chapter" data-level="4.3.2" data-path="pruebas-de-hipótesis-para-underlineboldsymbolmu.html"><a href="pruebas-de-hipótesis-para-underlineboldsymbolmu.html#pruebas-de-hipótesis-para-underlineboldsymbolmu-cuando-mathbfsigma-es-conocida-población-normal"><i class="fa fa-check"></i><b>4.3.2</b> Pruebas de Hipótesis para <span class="math inline">\(\underline{\boldsymbol{\mu}}\)</span> cuando <span class="math inline">\(\mathbf{\Sigma}\)</span> es Conocida (Población: Normal)</a></li>
<li class="chapter" data-level="4.3.3" data-path="pruebas-de-hipótesis-para-underlineboldsymbolmu.html"><a href="pruebas-de-hipótesis-para-underlineboldsymbolmu.html#pruebas-de-hipótesis-para-underlineboldsymbolmu-en-muestra-grande"><i class="fa fa-check"></i><b>4.3.3</b> Pruebas de Hipótesis para <span class="math inline">\(\underline{\boldsymbol{\mu}}\)</span> en Muestra Grande</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html"><a href="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html"><i class="fa fa-check"></i><b>4.4</b> PH para Igualdad de Vectores de Medias Poblacionales <span class="math inline">\(\underline{\boldsymbol{\mu}}_1=\underline{\boldsymbol{\mu}}_2\)</span></a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html"><a href="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html#caso-1.-mathbfsigma_1mathbfsigma_2mathbfsigma-conocida"><i class="fa fa-check"></i><b>4.4.1</b> Caso-1. <span class="math inline">\(\mathbf{\Sigma}_1=\mathbf{\Sigma}_2=\mathbf{\Sigma}\)</span>-Conocida</a></li>
<li class="chapter" data-level="4.4.2" data-path="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html"><a href="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html#caso-2.-mathbfsigma_1mathbfsigma_2mathbfsigma-desconocida"><i class="fa fa-check"></i><b>4.4.2</b> Caso-2. <span class="math inline">\(\mathbf{\Sigma}_1=\mathbf{\Sigma}_2=\mathbf{\Sigma}\)</span>-Desconocida</a></li>
<li class="chapter" data-level="4.4.3" data-path="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html"><a href="ph-para-igualdad-de-vectores-de-medias-poblacionales-underlineboldsymbolmu_1underlineboldsymbolmu_2.html#caso-3.-mathbfsigma_1neq-mathbfsigma_2-desconocida"><i class="fa fa-check"></i><b>4.4.3</b> Caso-3. <span class="math inline">\(\mathbf{\Sigma}_1\neq \mathbf{\Sigma}_2\)</span>-Desconocida</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html"><a href="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html"><i class="fa fa-check"></i><b>4.5</b> Pruebas de Hipótesis Acerca de dos Vectores de Medias Poblacionales <span class="math inline">\(\underline{\boldsymbol{\mu}}_1\)</span> y <span class="math inline">\(\underline{\boldsymbol{\mu}}_2\)</span>,   para muestras grandes</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html"><a href="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html#caso-1.-mathbfsigma_1mathbfsigma_2mathbfsigma-conocida-1"><i class="fa fa-check"></i><b>4.5.1</b> Caso-1. <span class="math inline">\(\mathbf{\Sigma}_1=\mathbf{\Sigma}_2=\mathbf{\Sigma}\)</span>-Conocida</a></li>
<li class="chapter" data-level="4.5.2" data-path="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html"><a href="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html#caso-2.-mathbfsigma_1mathbfsigma_2mathbfsigma-desconocida-1"><i class="fa fa-check"></i><b>4.5.2</b> Caso-2. <span class="math inline">\(\mathbf{\Sigma}_1=\mathbf{\Sigma}_2=\mathbf{\Sigma}\)</span>-Desconocida</a></li>
<li class="chapter" data-level="4.5.3" data-path="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html"><a href="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-para-muestras-grandes.html#caso-3.-mathbfsigma_1-neq-mathbfsigma_2-desconocidas"><i class="fa fa-check"></i><b>4.5.3</b> Caso-3. <span class="math inline">\(\mathbf{\Sigma}_1 \neq \mathbf{\Sigma}_2\)</span>-Desconocidas</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-observaciones-pareadas.html"><a href="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-observaciones-pareadas.html"><i class="fa fa-check"></i><b>4.6</b> Pruebas de Hipótesis Acerca de dos Vectores de Medias Poblacionales <span class="math inline">\(\underline{\boldsymbol{\mu}}_1\)</span> y <span class="math inline">\(\underline{\boldsymbol{\mu}}_2\)</span>,      Observaciones Pareadas</a></li>
<li class="chapter" data-level="4.7" data-path="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html"><a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html"><i class="fa fa-check"></i><b>4.7</b> PH Acerca de Contrastes para el vector de medias Poblacional <span class="math inline">\(\underline{\boldsymbol{\mu}}\)</span>, de una <span class="math inline">\(N_p(\underline{\boldsymbol{\mu}} \ , \ \mathbf{\Sigma} )\)</span></a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html"><a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html#mathbfsigma-desconocida"><i class="fa fa-check"></i><b>4.7.1</b> <span class="math inline">\(\mathbf{\Sigma}\)</span>-desconocida</a></li>
<li class="chapter" data-level="4.7.2" data-path="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html"><a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html#mathbfsigma-es-conocida"><i class="fa fa-check"></i><b>4.7.2</b> <span class="math inline">\(\mathbf{\Sigma}\)</span>-es conocida</a></li>
<li class="chapter" data-level="4.7.3" data-path="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html"><a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html#mathbfsigma-desconocida-y-n-grande"><i class="fa fa-check"></i><b>4.7.3</b> <span class="math inline">\(\mathbf{\Sigma}\)</span>-Desconocida y n-Grande</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="inferencia-para-la-matriz-de-covarianza.html"><a href="inferencia-para-la-matriz-de-covarianza.html"><i class="fa fa-check"></i><b>4.8</b> Inferencia para la Matriz de Covarianza</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="inferencia-para-la-matriz-de-covarianza.html"><a href="inferencia-para-la-matriz-de-covarianza.html#pruba-de-razón-de-verosimilitud"><i class="fa fa-check"></i><b>4.8.1</b> Pruba de Razón de Verosimilitud</a></li>
<li class="chapter" data-level="4.8.2" data-path="inferencia-para-la-matriz-de-covarianza.html"><a href="inferencia-para-la-matriz-de-covarianza.html#prueba-de-bartlet"><i class="fa fa-check"></i><b>4.8.2</b> Prueba de Bartlet</a></li>
<li class="chapter" data-level="4.8.3" data-path="inferencia-para-la-matriz-de-covarianza.html"><a href="inferencia-para-la-matriz-de-covarianza.html#dos-o-más-matrices-de-covarianzas"><i class="fa fa-check"></i><b>4.8.3</b> Dos o más Matrices de Covarianzas</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><i class="fa fa-check"></i><b>4.9</b> Regiones de Confianza y comparaciones simultáneas entre las componentes del vector de medias <span class="math inline">\(\underline{\mu}\)</span></a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html#construcción-de-una-región-de-confianza-para-underlinemu-cuando-la-población-tiene-distribución-n_punderlinemumathbfsigma-con-underlinemu-y-mathbfsigma-desconocidos"><i class="fa fa-check"></i><b>4.9.1</b> Construcción de una región de confianza para <span class="math inline">\(\underline{\mu}\)</span> cuando la población tiene distribución <span class="math inline">\(N_p(\underline{\mu},\mathbf{\Sigma})\)</span>, con <span class="math inline">\(\underline{\mu}\)</span> y <span class="math inline">\(\mathbf{\Sigma}\)</span> desconocidos</a></li>
<li class="chapter" data-level="4.9.2" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html#región-de-confianza-para-el-caso-de-p2-elipse-de-confianza"><i class="fa fa-check"></i><b>4.9.2</b> Región de Confianza para el caso de <span class="math inline">\(p=2\)</span> (Elipse de Confianza)</a></li>
<li class="chapter" data-level="4.9.3" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html#intervalos-de-confianza-simultáneos-para-las-componentes-del-vector-de-medias-underlinemu"><i class="fa fa-check"></i><b>4.9.3</b> Intervalos de confianza simultáneos para las componentes del vector de medias <span class="math inline">\(\underline{\mu}\)</span></a></li>
<li class="chapter" data-level="4.9.4" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html#ic-t2-simultáneos-para-diferencias-de-medias"><i class="fa fa-check"></i><b>4.9.4</b> IC <span class="math inline">\(T^2\)</span> Simultáneos para Diferencias de Medias</a></li>
<li class="chapter" data-level="4.9.5" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html#método-de-bonferroni-para-comparaciones-múltiples"><i class="fa fa-check"></i><b>4.9.5</b> Método de Bonferroni para Comparaciones Múltiples</a></li>
<li class="chapter" data-level="4.9.6" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html#intervalos-de-confianza-simultáneos-chi2-caso-n-grande"><i class="fa fa-check"></i><b>4.9.6</b> Intervalos de Confianza Simultáneos <span class="math inline">\(\chi^2\)</span> (caso n-Grande)</a></li>
<li class="chapter" data-level="4.9.7" data-path="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html"><a href="regiones-de-confianza-y-comparaciones-simultáneas-entre-las-componentes-del-vector-de-medias-underlinemu.html#ic-simultáneos-para-n-grande-usando-la-normal-estándar-z_alpha"><i class="fa fa-check"></i><b>4.9.7</b> IC simultáneos para n-Grande Usando la Normal Estándar <span class="math inline">\(Z_\alpha\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ACP.html"><a href="ACP.html"><i class="fa fa-check"></i><b>5</b> Análisis de Componentes Principales (AC)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introducción-1.html"><a href="introducción-1.html"><i class="fa fa-check"></i><b>5.1</b> Introducción</a></li>
<li class="chapter" data-level="5.2" data-path="interpretación-del-acp.html"><a href="interpretación-del-acp.html"><i class="fa fa-check"></i><b>5.2</b> Interpretación del ACP</a></li>
<li class="chapter" data-level="5.3" data-path="interpretación-geométrica-del-acp-mediante-un-ejemplo-simple.html"><a href="interpretación-geométrica-del-acp-mediante-un-ejemplo-simple.html"><i class="fa fa-check"></i><b>5.3</b> Interpretación Geométrica del ACP Mediante un Ejemplo Simple</a></li>
<li class="chapter" data-level="5.4" data-path="mas-de-dos-ejes.html"><a href="mas-de-dos-ejes.html"><i class="fa fa-check"></i><b>5.4</b> Mas de dos Ejes</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="mas-de-dos-ejes.html"><a href="mas-de-dos-ejes.html#min-cuadrados"><i class="fa fa-check"></i><b>5.4.1</b> Ajuste de Mínimos Cuadrados</a></li>
<li class="chapter" data-level="5.4.2" data-path="mas-de-dos-ejes.html"><a href="mas-de-dos-ejes.html#relación-entre-los-sub-espacios-de-mathbbrp-y-de-mathbbrn"><i class="fa fa-check"></i><b>5.4.2</b> Relación entre los Sub-espacios de <span class="math inline">\(\mathbb{R}^p\)</span> y de <span class="math inline">\(\mathbb{R}^n\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="componentes-principales-en-análisis-de-regresión.html"><a href="componentes-principales-en-análisis-de-regresión.html"><i class="fa fa-check"></i><b>5.5</b> Componentes Principales en Análisis de Regresión</a></li>
<li class="chapter" data-level="5.6" data-path="componentes-principales-poblacionales.html"><a href="componentes-principales-poblacionales.html"><i class="fa fa-check"></i><b>5.6</b> Componentes Principales Poblacionales</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="componentes-principales-poblacionales.html"><a href="componentes-principales-poblacionales.html#determinación-de-las-cps"><i class="fa fa-check"></i><b>5.6.1</b> Determinación de las CPs</a></li>
<li class="chapter" data-level="5.6.2" data-path="componentes-principales-poblacionales.html"><a href="componentes-principales-poblacionales.html#componentes-principales-derivadas-de-una-normal-multivariada"><i class="fa fa-check"></i><b>5.6.2</b> Componentes Principales Derivadas de una Normal Multivariada</a></li>
<li class="chapter" data-level="5.6.3" data-path="componentes-principales-poblacionales.html"><a href="componentes-principales-poblacionales.html#componentes-principales-usando-variables-estandarizadas"><i class="fa fa-check"></i><b>5.6.3</b> Componentes principales usando variables estandarizadas</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="componentes-principales-para-matrices-de-var-cov-mathbfsigma-con-estructuras-especiales.html"><a href="componentes-principales-para-matrices-de-var-cov-mathbfsigma-con-estructuras-especiales.html"><i class="fa fa-check"></i><b>5.7</b> Componentes Principales para Matrices de Var-Cov <span class="math inline">\(\mathbf{\Sigma}\)</span> con Estructuras Especiales</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="componentes-principales-para-matrices-de-var-cov-mathbfsigma-con-estructuras-especiales.html"><a href="componentes-principales-para-matrices-de-var-cov-mathbfsigma-con-estructuras-especiales.html#variables-no-correlacionadas"><i class="fa fa-check"></i><b>5.7.1</b> Variables No-Correlacionadas</a></li>
<li class="chapter" data-level="5.7.2" data-path="componentes-principales-para-matrices-de-var-cov-mathbfsigma-con-estructuras-especiales.html"><a href="componentes-principales-para-matrices-de-var-cov-mathbfsigma-con-estructuras-especiales.html#variables-altamente-correlacionadas"><i class="fa fa-check"></i><b>5.7.2</b> Variables Altamente Correlacionadas</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="componentes-principales-muestrales.html"><a href="componentes-principales-muestrales.html"><i class="fa fa-check"></i><b>5.8</b> Componentes Principales Muestrales</a></li>
<li class="chapter" data-level="5.9" data-path="algunos-ejemplos.html"><a href="algunos-ejemplos.html"><i class="fa fa-check"></i><b>5.9</b> Algunos Ejemplos</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="algunos-ejemplos.html"><a href="algunos-ejemplos.html#ejemplo-2"><i class="fa fa-check"></i><b>5.9.1</b> Ejemplo-2</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="cómo-elegir-el-número-de-componentes-principales.html"><a href="cómo-elegir-el-número-de-componentes-principales.html"><i class="fa fa-check"></i><b>5.10</b> Cómo elegir el número de Componentes Principales?</a></li>
<li class="chapter" data-level="5.11" data-path="interpretación-de-las-componentes-principales-muestrales.html"><a href="interpretación-de-las-componentes-principales-muestrales.html"><i class="fa fa-check"></i><b>5.11</b> Interpretación de las componentes principales muestrales</a></li>
<li class="chapter" data-level="5.12" data-path="estandarización-de-las-componentes-principales-muestrales.html"><a href="estandarización-de-las-componentes-principales-muestrales.html"><i class="fa fa-check"></i><b>5.12</b> Estandarización de las componentes principales muestrales</a></li>
<li class="chapter" data-level="5.13" data-path="gráficos-en-una-análisis-de-componentes-principales.html"><a href="gráficos-en-una-análisis-de-componentes-principales.html"><i class="fa fa-check"></i><b>5.13</b> Gráficos en una Análisis de componentes principales</a>
<ul>
<li class="chapter" data-level="5.13.1" data-path="gráficos-en-una-análisis-de-componentes-principales.html"><a href="gráficos-en-una-análisis-de-componentes-principales.html#el-gráfico-biplot"><i class="fa fa-check"></i><b>5.13.1</b> El gráfico biplot:</a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="propiedades-de-hatlambda_i-y-underlinehate_i-en-muestras-grandes.html"><a href="propiedades-de-hatlambda_i-y-underlinehate_i-en-muestras-grandes.html"><i class="fa fa-check"></i><b>5.14</b> Propiedades de <span class="math inline">\(\hat{\lambda}_i\)</span> y <span class="math inline">\(\underline{\hat{e}}_i\)</span> en muestras grandes</a></li>
<li class="chapter" data-level="5.15" data-path="ejemplos-finales.html"><a href="ejemplos-finales.html"><i class="fa fa-check"></i><b>5.15</b> Ejemplos Finales</a>
<ul>
<li class="chapter" data-level="5.15.1" data-path="ejemplos-finales.html"><a href="ejemplos-finales.html#ejemplo-1"><i class="fa fa-check"></i><b>5.15.1</b> Ejemplo-1</a></li>
<li class="chapter" data-level="5.15.2" data-path="ejemplos-finales.html"><a href="ejemplos-finales.html#ejemplo-2-1"><i class="fa fa-check"></i><b>5.15.2</b> Ejemplo-2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliografía.html"><a href="bibliografía.html"><i class="fa fa-check"></i>Bibliografía</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Chapter 4</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> PH Acerca de Contrastes para el vector de medias Poblacional <span class="math inline">\(\underline{\boldsymbol{\mu}}\)</span>, de una <span class="math inline">\(N_p(\underline{\boldsymbol{\mu}} \ , \ \mathbf{\Sigma} )\)</span><a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html#ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="mathbfsigma-desconocida" class="section level3 hasAnchor" number="4.7.1">
<h3><span class="header-section-number">4.7.1</span> <span class="math inline">\(\mathbf{\Sigma}\)</span>-desconocida<a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html#mathbfsigma-desconocida" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sea <span class="math inline">\(\underline{\mathbf{x}_1},\underline{\mathbf{x}_2},\cdots,\underline{\mathbf{x}_n}\)</span> una m.a de una población normal <span class="math inline">\(p\)</span>-variada con vector de medias <span class="math inline">\(\underline{\boldsymbol{\mu}}\)</span>-desconocido y matriz de varianzas-covarianzas <span class="math inline">\(\mathbf{\Sigma}\)</span>- desconocida, ie. <span class="math inline">\(\underline{\mathbf{x}_i} \sim N_p( \underline{\boldsymbol{\mu}}\ , \ \mathbf{\Sigma})\)</span></p>
<p>Sea <span class="math inline">\(C_{r \times p}\)</span>-una matriz de constantes. <span class="math inline">\(C\)</span>-contiene los coeficientes para <span class="math inline">\(r\)</span>-combinaciones lineales simultáneas de las componentes de <span class="math inline">\(\underline{\boldsymbol{\mu}}=(\mu_1,\mu_2,\ldots,\mu_p)^t\)</span>, es decir:
<span class="math display">\[
C \underline{\boldsymbol{\mu}}= \begin{bmatrix}
c_{11} &amp; c_{12} &amp; \cdots &amp; c_{1p}\\
c_{21} &amp; c_{22} &amp; \cdots &amp; c_{2p}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
c_{r1} &amp; c_{r2} &amp; \cdots &amp; c_{rp}\\
\end{bmatrix}\begin{bmatrix}
\mu_1 \\ \mu_2 \\ \vdots \\ \mu_p
\end{bmatrix}=\begin{bmatrix}
c_{11}\mu_1 + c_{12}\mu_2 + \cdots + c_{1p}\mu_p \\
c_{21}\mu_1 + c_{22}\mu_2 + \cdots + c_{2p}\mu_p \\
\\
c_{r1}\mu_1 + c_{r2}\mu_2 + \cdots + c_{rp}\mu_p
\end{bmatrix}_{r \times 1}
\]</span></p>
<p>Se desea contrastar las hipótesis:
<span class="math display">\[
\begin{cases}
H_0 \ : \  C \underline{\boldsymbol{\mu}} = \underline{\boldsymbol{\gamma}} \\
H_0 \ : \  C \underline{\boldsymbol{\mu}} \neq \underline{\boldsymbol{\gamma}}
\end{cases} \ , \ \ \ \text{con} \ \ \ \underline{\boldsymbol{\gamma}}=\begin{pmatrix}
\gamma_1 \\ \gamma_2 \\ \vdots \\ \gamma_r
\end{pmatrix}-\text{Vector de Constantes}.
\]</span></p>
<p>Un estimador insesgado para <span class="math inline">\(C \underline{\boldsymbol{\mu}}\)</span> es:
<span class="math inline">\(C \underline{\overline{\mathbf{x}}}\)</span>, el cual tiene la siguiente distribución:</p>
<p><span class="math display">\[
C \underline{\overline{\mathbf{x}}} \sim N_r \left(C \underline{\boldsymbol{\mu}} \ , \ C \mathbf{\Sigma}_{\underline{\overline{\mathbf{x}}}} C^t  \right) \ \ , \ \ \text{es decir}:
\]</span>
<span class="math display">\[
C \underline{\overline{\mathbf{x}}} \sim N_r \left(C \underline{\boldsymbol{\mu}} \ , \  \frac{1}{n} C \mathbf{\Sigma} C^t  \right), \ \ \ \text{pues}:\ \ \ \mathbf{\Sigma}_{\underline{\overline{\mathbf{x}}}}=\frac{\mathbf{\Sigma}}{n}.
\]</span></p>
<p>Como <span class="math inline">\(\mathbf{\Sigma}\)</span>-es desconocida se usa la estadística de prueba:
<span class="math display">\[
T_0^2= n (C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}})^t [C \mathbf{S} C^t]^{-1}(C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}}) \sim \frac{(n-1)r}{n-r}F_{r,n-r}.
\]</span>
Se rechaza <span class="math inline">\(H_0\)</span> :    si <span class="math inline">\(T_0^2 &gt; \frac{(n-1)r}{n-r}F_{\alpha;\ r,n-r}\)</span>.</p>
<div class="example">
<p><span id="exm:ejemplo1-ph-contrastes-Cmu" class="example"><strong>Ejemplo 4.16  (Ejemplo-1 PH de Contrastes de Medias) </strong></span>Los datos contenidos en la siguiente tabla, corresponden a los pesos (en gramos) del corcho encontrado en muestras tomadas de 28 árboles cultivados en una parcela experimental. Estas muestras fueron tomadas en 4-direcciones: Norte (N), este (E), sur (S) y oeste (O). En este caso se tienen 4-variables, que corresponden a las mediciones tomadas en cada dirección. Se quiere verificar si los pesos medios de corcho son iguales en la dirección norte-sur y en la dirección este-oeste. Se asume que estas cuatro mediciones tienen una distribución normal 4-variada, con vector de medias <span class="math inline">\(\underline{\boldsymbol{\mu}}=(\mu_N , \ \mu_E ,\ \mu_S ,\ \mu_O)\)</span> y matriz de varianzas-covarianzas <span class="math inline">\(\mathbf{\Sigma}\)</span>, ambas cantidades desconocidas. Es decir se desea probar: <span class="math inline">\(H_0 \ : \ \mu_1=\mu_3 \ \ \text{y} \ \ \mu_2=\mu_4\)</span>.</p>
</div>
<table>
<caption><span id="tab:unnamed-chunk-31">Tabla 4.15: </span>Conjunto de Datos del Ejemplo-1</caption>
<thead>
<tr class="header">
<th align="center">X1</th>
<th align="center">X2</th>
<th align="center">X3</th>
<th align="center">X4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">72</td>
<td align="center">66</td>
<td align="center">76</td>
<td align="center">77</td>
</tr>
<tr class="even">
<td align="center">60</td>
<td align="center">53</td>
<td align="center">66</td>
<td align="center">63</td>
</tr>
<tr class="odd">
<td align="center">56</td>
<td align="center">57</td>
<td align="center">64</td>
<td align="center">58</td>
</tr>
<tr class="even">
<td align="center">41</td>
<td align="center">29</td>
<td align="center">36</td>
<td align="center">38</td>
</tr>
<tr class="odd">
<td align="center">32</td>
<td align="center">32</td>
<td align="center">35</td>
<td align="center">36</td>
</tr>
<tr class="even">
<td align="center">30</td>
<td align="center">35</td>
<td align="center">34</td>
<td align="center">26</td>
</tr>
<tr class="odd">
<td align="center">39</td>
<td align="center">39</td>
<td align="center">31</td>
<td align="center">27</td>
</tr>
<tr class="even">
<td align="center">42</td>
<td align="center">43</td>
<td align="center">31</td>
<td align="center">25</td>
</tr>
<tr class="odd">
<td align="center">37</td>
<td align="center">40</td>
<td align="center">31</td>
<td align="center">25</td>
</tr>
<tr class="even">
<td align="center">33</td>
<td align="center">29</td>
<td align="center">27</td>
<td align="center">36</td>
</tr>
<tr class="odd">
<td align="center">32</td>
<td align="center">30</td>
<td align="center">34</td>
<td align="center">28</td>
</tr>
<tr class="even">
<td align="center">63</td>
<td align="center">45</td>
<td align="center">74</td>
<td align="center">63</td>
</tr>
<tr class="odd">
<td align="center">54</td>
<td align="center">46</td>
<td align="center">60</td>
<td align="center">52</td>
</tr>
<tr class="even">
<td align="center">47</td>
<td align="center">51</td>
<td align="center">52</td>
<td align="center">43</td>
</tr>
<tr class="odd">
<td align="center">91</td>
<td align="center">79</td>
<td align="center">100</td>
<td align="center">75</td>
</tr>
<tr class="even">
<td align="center">56</td>
<td align="center">68</td>
<td align="center">47</td>
<td align="center">50</td>
</tr>
<tr class="odd">
<td align="center">79</td>
<td align="center">65</td>
<td align="center">70</td>
<td align="center">61</td>
</tr>
<tr class="even">
<td align="center">81</td>
<td align="center">80</td>
<td align="center">68</td>
<td align="center">58</td>
</tr>
<tr class="odd">
<td align="center">78</td>
<td align="center">55</td>
<td align="center">67</td>
<td align="center">60</td>
</tr>
<tr class="even">
<td align="center">46</td>
<td align="center">38</td>
<td align="center">37</td>
<td align="center">38</td>
</tr>
<tr class="odd">
<td align="center">39</td>
<td align="center">35</td>
<td align="center">34</td>
<td align="center">37</td>
</tr>
<tr class="even">
<td align="center">32</td>
<td align="center">30</td>
<td align="center">30</td>
<td align="center">32</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">50</td>
<td align="center">67</td>
<td align="center">54</td>
</tr>
<tr class="even">
<td align="center">35</td>
<td align="center">37</td>
<td align="center">48</td>
<td align="center">39</td>
</tr>
<tr class="odd">
<td align="center">39</td>
<td align="center">36</td>
<td align="center">39</td>
<td align="center">31</td>
</tr>
<tr class="even">
<td align="center">50</td>
<td align="center">34</td>
<td align="center">37</td>
<td align="center">40</td>
</tr>
<tr class="odd">
<td align="center">43</td>
<td align="center">37</td>
<td align="center">39</td>
<td align="center">50</td>
</tr>
<tr class="even">
<td align="center">48</td>
<td align="center">54</td>
<td align="center">57</td>
<td align="center">43</td>
</tr>
</tbody>
</table>
<p>Esta hipótesis se puede expresar como:
<span class="math display">\[
\begin{cases}
H_0 \ : \  C \underline{\boldsymbol{\mu}} = \underline{\boldsymbol{\gamma}} \\ \\
H_0 \ : \  C \underline{\boldsymbol{\mu}} \neq \underline{\boldsymbol{\gamma}}
\end{cases} \ \ \ \ \Longleftrightarrow \ \ \ \ \ \begin{cases}
H_0 \ : \  \begin{bmatrix}
1 &amp; 0 &amp; -1 &amp; 0 \\ 0 &amp; 1 &amp; 0 &amp; -1
\end{bmatrix}\begin{bmatrix}
\mu_1 \\ \mu_2 \\ \mu_3 \\ \mu_4
\end{bmatrix} = \begin{bmatrix}
0 \\ 0
\end{bmatrix} \\ \\
H_0 \ : \  \begin{bmatrix}
1 &amp; 0 &amp; -1 &amp; 0 \\ 0 &amp; 1 &amp; 0 &amp; -1
\end{bmatrix} \begin{bmatrix}
\mu_1 \\ \mu_2 \\ \mu_3 \\ \mu_4
\end{bmatrix} \neq \begin{bmatrix}
0 \\ 0
\end{bmatrix}
\end{cases}
\]</span>
<span class="math display">\[
  \ \ \ \ \Longleftrightarrow \ \ \ \ \  \begin{cases}
H_0 \ : \  \mu_1-\mu_3=0\ \ \ , \ \ \   \mu_2-\mu_4=0 \\ \\
H_0 \ : \  \mu_1- \mu_3\neq 0\ \ \ , \ \ \   \mu_2-\mu_4\neq 0
\end{cases}\ \ \ \ \Longleftrightarrow \ \ \ \ \  \begin{cases}
H_0 \ : \  \mu_1=\mu_3\ \ \ , \ \ \   \mu_2=\mu_4 \\ \\
H_0 \ : \  \mu_1\neq \mu_3\ \ \ , \ \ \   \mu_2\neq\mu_4
\end{cases}
\]</span></p>
<p>Es decir que en este caso se tiene que:
<span class="math display">\[
C=\begin{bmatrix}
1 &amp; 0 &amp; -1 &amp; 0 \\ 0 &amp; 1 &amp; 0 &amp; -1
\end{bmatrix} \ \ \  , \ \ \ \ \underline{\boldsymbol{\gamma}} =\begin{bmatrix}
0 \\ 0
\end{bmatrix}\ \ \ \ \text{y}\ \ \ \ \ \underline{\boldsymbol{\mu}}=\begin{bmatrix}
\mu_1 \\ \mu_2 \\ \mu_3 \\ \mu_4
\end{bmatrix}.
\]</span></p>
<p>Después de realizar algunos cálculos previos, se obtiene el vector de medias y la matriz de var-cov muestrales dadas por:</p>
<p><span class="math display">\[
\underline{\overline{\mathbf{x}}}=\begin{bmatrix}
50.535\\ 46.179\\ 49.679\\ 45.179
\end{bmatrix}, \ \ \ \ \mathbf{S}=\begin{bmatrix}
290.41 &amp; 233.75 &amp; 288.44 &amp; 226.27 \\
&amp; 219.93 &amp; 229.06 &amp; 171.37 \\
&amp;&amp; 350.00 &amp; 259.54 \\
&amp;&amp;&amp; 226.00
\end{bmatrix}
\]</span></p>
<p>De igual forma se tiene que:
<span class="math display">\[
\mathbf{C}\underline{\overline{\mathbf{x}}}=\begin{bmatrix}
0.857 \\ 1.00
\end{bmatrix}, \ \ \ \ \ \mathbf{CSC}^t=\begin{bmatrix}
63.53 &amp; 27.96 \\ 27.96 &amp; 103.19
\end{bmatrix}
\]</span></p>
<p>Los resultados de dicha PH son:</p>
<pre><code>##       T2        K       F0      df1      df2  F_tabla  Valor_p 
##  0.44327  2.07692  0.21343  2.00000 26.00000  3.36902  0.80921</code></pre>
<p>Es decir que el Estadístico <span class="math inline">\(T^2\)</span> esta dado por:
<span class="math display">\[
T_0^2= n (C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}})^t [C \mathbf{S} C^t]^{-1}(C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}}) = 0.44327
\]</span></p>
<p>y el valor-p de la prueba es: 0.80921 de donde se conluye que como el valor-p=0.80921 &gt; 0.05 , entonces no se rechaza la hipótesis nula H0.</p>
<p>Similarmente el valor crítico de la tabla F-snedecor es:
<span class="math display">\[
F_{tabla}=F_{1-\alpha ; r, n-r}=F_{1-0.05 ; 2,  28-2}=F_{0.95 ; 2, 26}=3.3690164
\]</span>
de donde como el valor del <span class="math inline">\(F_0\)</span>-calculado,
<span class="math display">\[
F_0=\frac{1}{k}T_0^2=\frac{(n-r)}{(n-1)r}T_0^2=\frac{(28-2)}{(28-1)2}(0.44327)=0.2134263&lt; 3.3690164
\]</span></p>
<p>entonces no se rechaza la hipótesis nula H0.</p>
</div>
<div id="mathbfsigma-es-conocida" class="section level3 hasAnchor" number="4.7.2">
<h3><span class="header-section-number">4.7.2</span> <span class="math inline">\(\mathbf{\Sigma}\)</span>-es conocida<a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html#mathbfsigma-es-conocida" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En este caso se utiliza:
<span class="math display">\[
\chi_0^2= n (C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}})^t [C \mathbf{\Sigma} C^t]^{-1}(C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}}) \sim \chi_{r}^2.
\]</span>
Se rechaza <span class="math inline">\(H_0\)</span> :    si <span class="math inline">\(\chi_0^2 &gt; \chi_{\alpha; r}^2\)</span>.</p>
</div>
<div id="mathbfsigma-desconocida-y-n-grande" class="section level3 hasAnchor" number="4.7.3">
<h3><span class="header-section-number">4.7.3</span> <span class="math inline">\(\mathbf{\Sigma}\)</span>-Desconocida y n-Grande<a href="ph-acerca-de-contrastes-para-el-vector-de-medias-poblacional-underlineboldsymbolmu-de-una-n_punderlineboldsymbolmu-mathbfsigma.html#mathbfsigma-desconocida-y-n-grande" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En este caso se utiliza:
<span class="math display">\[
\chi_0^2= n (C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}})^t [C \mathbf{S} C^t]^{-1}(C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}}) \sim \chi_{r}^2.
\]</span></p>
<p>Se rechaza <span class="math inline">\(H_0\)</span> :    si <span class="math inline">\(\chi_0^2 &gt; \chi_{\alpha; r}^2\)</span>.</p>
<div class="example">
<p><span id="exm:ejemplo1-ph-contrastes-Cmu-ngrande" class="example"><strong>Ejemplo 4.17  (Ejemplo-1 PH de Contrastes para Medias n-Grande) </strong></span>Continuando con los datos del ejemplo <a href="inferencia-estadística-para-la-media-mu-caso-univariado.html#exm:ejemplo1-ph-uni">4.1</a>, donde se tienen los siguientes datos que corresponden a una muestra de tamaño <span class="math inline">\(n=100\)</span> y que se dividen en tres grupos o clases denotados por los números 1,2 y 3 de la variable <em>Clases</em>.</p>
</div>
<p>Se considera el conjunto de datos completo.</p>
<table>
<caption><span id="tab:unnamed-chunk-33">Tabla 4.16: </span>Encabezado de Datos Ejemplo-1</caption>
<thead>
<tr class="header">
<th align="center">X1</th>
<th align="center">X2</th>
<th align="center">X3</th>
<th align="center">Clases</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">-0.0758</td>
<td align="center">-2.2825</td>
<td align="center">-0.4553</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center">-0.1436</td>
<td align="center">-0.5651</td>
<td align="center">-0.5009</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">-1.8002</td>
<td align="center">-1.0732</td>
<td align="center">-0.4070</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center">-0.8298</td>
<td align="center">3.1684</td>
<td align="center">-2.8147</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">0.7292</td>
<td align="center">1.3984</td>
<td align="center">-1.2794</td>
<td align="center">1</td>
</tr>
<tr class="even">
<td align="center">-3.2951</td>
<td align="center">-6.1390</td>
<td align="center">-2.7887</td>
<td align="center">1</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{cases}
H_0 \ : \  C \underline{\boldsymbol{\mu}} = \underline{\boldsymbol{\gamma}} \\ \\
H_0 \ : \  C \underline{\boldsymbol{\mu}} \neq \underline{\boldsymbol{\gamma}}
\end{cases} \ \ \ \ \Longleftrightarrow \ \ \ \ \ \begin{cases}
H_0 \ : \  \begin{bmatrix}
1 &amp; 0 &amp; -1  \\ 0 &amp; 1 &amp;  -1
\end{bmatrix}\begin{bmatrix}
\mu_1 \\ \mu_2 \\ \mu_3
\end{bmatrix} = \begin{bmatrix}
0 \\ 0
\end{bmatrix} \\ \\
H_0 \ : \  \begin{bmatrix}
1 &amp; 0 &amp; -1  \\ 0 &amp; 1 &amp;  -1
\end{bmatrix} \begin{bmatrix}
\mu_1 \\ \mu_2 \\ \mu_3  
\end{bmatrix} \neq \begin{bmatrix}
0 \\ 0
\end{bmatrix}
\end{cases}
\]</span>
<span class="math display">\[
  \ \ \ \ \Longleftrightarrow \ \ \ \ \  \begin{cases}
H_0 \ : \  \mu_1-\mu_3=0\ \ \ , \ \ \   \mu_2-\mu_3=0 \\ \\
H_0 \ : \  \mu_1- \mu_3\neq 0\ \ \ , \ \ \   \mu_2-\mu_3\neq 0
\end{cases}\ \ \ \ \Longleftrightarrow \ \ \ \ \  \begin{cases}
H_0 \ : \  \mu_1=\mu_3\ \ \ , \ \ \   \mu_2=\mu_3 \\ \\
H_0 \ : \  \mu_1\neq \mu_3\ \ \ , \ \ \   \mu_2\neq\mu_3
\end{cases}
\]</span></p>
<p>Es decir que en este caso se tiene que:
<span class="math display">\[
C=\begin{bmatrix}
1 &amp; 0 &amp; -1  \\ 0 &amp; 1 &amp; -1
\end{bmatrix} \ \ \  , \ \ \ \ \underline{\boldsymbol{\gamma}} =\begin{bmatrix}
0 \\ 0
\end{bmatrix}\ \ \ \ \text{y}\ \ \ \ \ \underline{\boldsymbol{\mu}}=\begin{bmatrix}
\mu_1 \\ \mu_2 \\ \mu_3
\end{bmatrix}.
\]</span></p>
<p>Los resultados de dicha PH son:</p>
<pre><code>##     Chi_2        df Chi_tabla   Valor_p 
##   0.32131   2.00000   5.99146   0.85159</code></pre>
<p>Es decir que el Estadístico <span class="math inline">\(\chi^2\)</span> esta dado por:
<span class="math display">\[
\chi_0^2= n (C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}})^t [C \mathbf{S} C^t]^{-1}(C \underline{\overline{\mathbf{x}}} - \underline{\boldsymbol{\gamma}}) = 0.32131
\]</span></p>
<p>y el valor-p de la prueba es: 0.85159 de donde se conluye que como el valor-p=0.85159 &gt; 0.05 , entonces no se rechaza la hipótesis nula H0.</p>
<p>Similarmente el valor crítico de la tabla <span class="math inline">\(\chi^2\)</span> es:
<span class="math display">\[
\chi_{tabla}^2=\chi_{1-\alpha ; r}^2=\chi_{1-0.05 ; 2}^2=\chi_{0.95 ; 2}^2=5.9914645
\]</span>
de donde como el valor del <span class="math inline">\(\chi_0^2\)</span>-calculado,
<span class="math display">\[
\chi_0^2=0.32131 &lt; 5.9914645
\]</span></p>
<p>entonces no se rechaza la hipótesis nula H0.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pruebas-de-hipótesis-acerca-de-dos-vectores-de-medias-poblacionales-underlineboldsymbolmu_1-y-underlineboldsymbolmu_2-observaciones-pareadas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inferencia-para-la-matriz-de-covarianza.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-iam.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsubsection",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
